### PR TITLE
A, B Files: Contrail -> Tungsten Fabric

### PR DESCRIPTION
**Pull request by vmbrasseur**
Contrail -> Tungsten Fabric for a*.rst and b*.rst files.

### CODE REVIEW

**Review by tnaganawa — APPROVED** [review]
It looks good to me :)
Thanks for the great work!

**Comment by tnaganawa** [comment]
Sorry, I don't seem to have write access to this repo :(
"This branch has no conflicts with the base branch"
"Only those with write access to this repository can merge pull requests."

Hopefully, pono or swill will review and merge them ..

**Comment by vmbrasseur** [comment]
I've sent an invite for you to be a collaborator on this repo. Apologies for forgetting to do that earlier, @tnaganawa!

**Comment by vmbrasseur** [comment]
I've sent an invite for you to be a collaborator on this repo. Apologies for forgetting to do that earlier, @tnaganawa!

**Pull request merged**
